### ISSUE TITLE
Cannot use matplotlib in jupyter kernel from cvmfs build 

### ISSUE THREAD

**Issue by philippeg-ligo** [gwastro/pycbc#2330] opened 2018-09-21 19:16 UTC
version affected 1.12.3 distributed by cvmfs:
 from an existing jupyer/jupyterhub  setup create a jupyter kernel:
```bash 
source /cvmfs/oasis.opensciencegrid.org/ligo/sw/pycbc/x86_64_rhel_7/virtualenv/pycbc-v1.12.3/bin/activate
python -m install --user --name "pycbc1.12.13" --display-name="pycbc1.12.3"
deactivate
```

create a notebook using that kernel  with the following code:
```python
%matplotlib inline
from matplotlib import pyplot as plt
plt.plot(range(10))
```
you'll get the following error

```
<matplotlib.lines.Line2D at 0x7f02eef1acd0>]
AttributeErrorTraceback (most recent call last)
/cvmfs/oasis.opensciencegrid.org/ligo/sw/pycbc/x86_64_rhel_7/virtualenv/pycbc-v1.12.3/lib/python2.7/site-packages/ipykernel/pylab/backend_inline.pyc in show(close, block)
     37             display(
     38                 figure_manager.canvas.figure,
---> 39                 metadata=_fetch_figure_metadata(figure_manager.canvas.figure)
     40             )
     41     finally:

/cvmfs/oasis.opensciencegrid.org/ligo/sw/pycbc/x86_64_rhel_7/virtualenv/pycbc-v1.12.3/lib/python2.7/site-packages/ipykernel/pylab/backend_inline.pyc in _fetch_figure_metadata(fig)
    172     """Get some metadata to help with displaying a figure."""
    173     # determine if a background is needed for legibility
--> 174     if _is_transparent(fig.get_facecolor()):
    175         # the background is transparent
    176         ticksLight = _is_light([label.get_color()

/cvmfs/oasis.opensciencegrid.org/ligo/sw/pycbc/x86_64_rhel_7/virtualenv/pycbc-v1.12.3/lib/python2.7/site-packages/ipykernel/pylab/backend_inline.pyc in _is_transparent(color)
    193 def _is_transparent(color):
    194     """Determine transparency from alpha."""
--> 195     rgba = colors.to_rgba(color)
    196     return rgba[3] < .5

AttributeError: 'module' object has no attribute 'to_rgba'
```

**Comment by ahnitz** [comment] 2018-09-21 19:17
@spxiwh I'm assigning this to your since I'm not sure I'd be able to test this. 

@philippeg-ligo Is this using the caltech jupyter kernels? Or are you starting up jupyter from within the cvmfs environment? Do you get a specific error?

**Comment by duncan-brown** [comment] 2018-09-21 19:18
@philippeg-ligo is the error related to `hide_code` by any chance?

**Comment by duncan-brown** [comment] 2018-09-21 19:31
The issue is that the CVMFS install contains an old version of matplotlib which doesn't have the `to_rgb()` function that was added relatively recently. The version freeze is implemented at

https://github.com/gwastro/pycbc/blob/master/tools/einsteinathome/pycbc_build_eah.sh#L1073

This was frozen because we had issues with plots changing during the O2 analysis. I don't see any reason to freeze this any more, unless @spxiwh does.

**Comment by ahnitz** [comment] 2018-09-21 19:32
@philippeg-ligo Unfortunately, I don't have access to the CIT jupyterhub. I think someone within the LSC will have to check such as @spxiwh will have to check.

**Comment by spxiwh** [comment] 2018-09-28 10:18
This appears to be the error reported at bottom of this message:

https://github.com/scikit-hep/scikit-hep/issues/58

(which is also what @duncan-brown indicates). @duncan-brown I think we should now be using matplotlib from at least the 2.0 branch. Is the fix just to remove this line?

**Comment by tapaimarton** [comment] 2018-09-28 11:43
@spxiwh @duncan-brown I was testing a development branch today and running a workflow, where using matplotlib 2.2.3 led to some plotting plotting code failure, changing back the version to 1.5.3 fixed those issues, so when changing the version, expect failures.

**Comment by spxiwh** [comment] 2018-09-28 11:46
Okay, I'll try and run a test workflow with up-to-date packages and reproduce that ... Let's move that to another issue ticket though.

**Comment by duncan-brown** [comment] 2018-09-28 11:49
@spxiwh just change it to `pip install matplotlib` to get the latest (or another specific version of the latest is buggy).

**Comment by spxiwh** [comment] 2018-09-28 11:57
@duncan-brown Will do. It looks like the issue @tapaimarton refers to was already fixed by:

https://github.com/gwastro/pycbc/pull/2315

but matplotlib does seem to be clearing up their deprecated code from 1.X now ... So cases like this where we were using deprecated routines will be problems soon.

Closing this PR now @duncan-brown I'll assign the build script fix to you.

**Closed by spxiwh** 2018-09-28 11:58 UTC
